spring.application.name=crediYa

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/crediYa
spring.r2dbc.username=postgres
spring.r2dbc.password=12345

spring.sql.init.mode=always
spring.sql.init.platform=postgres
logging.level.org.springframework.r2dbc=DEBUG

